flags: {}
packages:
- '.'
- location:
    git: git@github.com:ghcjs/ghcjs-base.git
    commit: 552da6d30fd25857a2ee8eb995d01fd4ae606d22
  extra-dep: true
- location:
    git: git@github.com:ghcjs/ghcjs-ffiqq.git
    commit: da31b18582542fcfceade5ef6b2aca66662b9e20
  extra-dep: true
- location:
    git: git@github.com:plow-technologies/ghcjs-vdom.git
    commit: 1a0e687ee645b74d939f428d2b36eecfe169cf11
  extra-dep: true
- location:
    git: git@github.com:plow-technologies/stm-notify.git
    commit: f047ee8c82993e79f7241688748e220affda6a73
  extra-dep: true
resolver: lts-6.25
compiler: ghcjs-0.2.0.9006025_ghc-7.10.3
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.9006025_ghc-7.10.3:
         url: http://ghcjs.tolysz.org/lts-6.25-9006025.tar.gz
         sha1: 3c87228579b55c05e227a7876682c2a7d4c9c007