resolver: lts-5.12
compiler: ghcjs-0.2.0.20160414_ghc-7.10.3
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160414_ghc-7.10.3:
        url: https://s3.amazonaws.com/ghcjs/ghcjs-0.2.0.20160414_ghc-7.10.3.tar.gz
        sha1: 6d6f307503be9e94e0c96ef1308c7cf224d06be3

packages:
- '.'
- location:
    git: git@github.com:plow-technologies/valentine.git
    commit: 40add31066cef8decd43787685b86f84bc5f414a
  extra-dep: true
- location:
    git: git@github.com:plow-technologies/stm-notify.git
    commit: f047ee8c82993e79f7241688748e220affda6a73
  extra-dep: true
- location:
    git: git@github.com:ghcjs/ghcjs-ffiqq.git
    commit: b52338c2dcd3b0707bc8aff2e171411614d4aedb
  extra-dep: true
- location:
    git: git@github.com:plow-technologies/ghcjs-vdom.git
    commit: 4bab395f9454383962ad86f1d00334b63ee8acee
  extra-dep: true

extra-deps:
- special-keys-0.1.0.3
- th-lift-instances-0.1.10
- th-lift-0.7.6
- path-pieces-0.2.1
- reflection-2.1.2
- safe-0.3.9
- transformers-compat-0.5.1.4
- utf8-string-1.0.1.1
- aeson-serialize-0.0.0
- network-info-0.2.0.8
- prelude-extras-0.4.0.3
