module LiveVDom.UserTypes (LiveVDom) where

import           LiveVDom.Adapter.Types
import qualified LiveVDom.Types as Types
import           GHCJS.VDOM.Attribute

-- | LiveVDom elements, generated by valentine and consumed by 'runDom'
type LiveVDom = Types.LiveVDom Attribute
