module LiveVDom.UserTypes (LiveVDom) where

import           LiveVDom.Adapter.Types
import           LiveVDom.Types 
import           GHCJS.VDOM.Attribute

-- | LiveVDom elements, generated by valentine and consumed by 'runDom'
-- type LiveVDom = Types.LiveVDom Attribute
